import requests
from bs4 import BeautifulSoup
import random
from pprint import pprint
import pandas as pd

all_search = [
'Afghanistan crypto ownership',
'Albania crypto ownership',
'Algeria crypto ownership',
'Angola crypto ownership',
'Argentina crypto ownership',
'Armenia crypto ownership',
'Australia crypto ownership',
'Austria crypto ownership',
'Azerbaijan crypto ownership',
'Bahamas crypto ownership',
'Bahrain crypto ownership',
'Bangladesh crypto ownership',
'Barbados crypto ownership',
'Belarus crypto ownership',
'Belgium crypto ownership',
'Belize crypto ownership',
'Benin crypto ownership',
'Bermuda crypto ownership',
'Bolivia crypto ownership',
'Bosnia and Herzegovina crypto ownership',
'Botswana crypto ownership',
'Brazil crypto ownership',
'Brunei Darussalam crypto ownership',
'Bulgaria crypto ownership',
'Burkina Faso crypto ownership',
'Cabo Verde crypto ownership',
'Cambodia crypto ownership',
'Cameroon crypto ownership',
'Canada crypto ownership',
'Cayman Islands crypto ownership',
'Chile crypto ownership',
'China crypto ownership',
'Colombia crypto ownership',
'Costa Rica crypto ownership',
'Croatia crypto ownership',
'Cuba crypto ownership',
'Cyprus crypto ownership',
'Czech Republic crypto ownership',
'Democratic Republic of Congo crypto ownership',
'Denmark crypto ownership',
'Dominican Republic crypto ownership',
'Ecuador crypto ownership',
'Egypt crypto ownership',
'El Salvador crypto ownership',
'Estonia crypto ownership',
'Ethiopia crypto ownership',
'Fiji crypto ownership',
'Finland crypto ownership',
'France crypto ownership',
'French Polynesia crypto ownership',
'Gabon crypto ownership',
'Georgia crypto ownership',
'Germany crypto ownership',
'Ghana crypto ownership',
'Greece crypto ownership',
'Guatemala crypto ownership',
'Guyana crypto ownership',
'Haití crypto ownership',
'Honduras crypto ownership',
'Hong Kong crypto ownership',
'Hungary crypto ownership',
'Iceland crypto ownership',
'India crypto ownership',
'Indonesia crypto ownership',
'Iran crypto ownership',
'Iraq crypto ownership',
'Ireland crypto ownership',
'Israel crypto ownership',
'Italy crypto ownership',
'Ivory Coast crypto ownership',
'Jamaica crypto ownership',
'Japan crypto ownership',
'Jordan crypto ownership',
'Kazakhstan crypto ownership',
'Kenya crypto ownership',
'Kuwait crypto ownership',
'Kyrgyzstan crypto ownership',
'Laos crypto ownership',
'Latvia crypto ownership',
'Lebanon crypto ownership',
'Libya crypto ownership',
'Lithuania crypto ownership',
'Luxembourg crypto ownership',
'Macao crypto ownership',
'Madagascar crypto ownership',
'Malawi crypto ownership',
'Malaysia crypto ownership',
'Maldives crypto ownership',
'Mali crypto ownership',
'Malta crypto ownership',
'Mauritius crypto ownership',
'Mexico crypto ownership',
'Moldova, Republic of crypto ownership',
'Monaco crypto ownership',
'Mongolia crypto ownership',
'Montenegro crypto ownership',
'Morocco crypto ownership',
'Mozambique crypto ownership',
'Myanmar crypto ownership',
'Namibia crypto ownership',
'Nepal crypto ownership',
'Netherlands crypto ownership',
'New Caledonia crypto ownership',
'New Zealand crypto ownership',
'Nicaragua crypto ownership',
'Nigeria crypto ownership',
'North Macedonia crypto ownership',
'Norway crypto ownership',
'Oman crypto ownership',
'Pakistan crypto ownership',
'Panama crypto ownership',
'Papua New Guinea crypto ownership',
'Paraguay crypto ownership',
'Peru crypto ownership',
'Philippines crypto ownership',
'Poland crypto ownership',
'Portugal crypto ownership',
'Puerto Rico crypto ownership',
'Qatar crypto ownership',
'Romania crypto ownership',
'Russia crypto ownership',
'Rwanda crypto ownership',
'Saudi Arabia crypto ownership',
'Senegal crypto ownership',
'Serbia crypto ownership',
'Seychelles crypto ownership',
'Singapore crypto ownership',
'Slovakia crypto ownership',
'Slovenia crypto ownership',
'South Africa crypto ownership',
'South Korea crypto ownership',
'Spain crypto ownership',
'Sri Lanka crypto ownership numbers',
'Suriname crypto ownership',
'Sweden crypto ownership',
'Switzerland crypto ownership',
'Syria crypto ownership',
'Tajikistan crypto ownership',
'Tanzania crypto ownership',
'Thailand crypto ownership',
'Togo crypto ownership',
'Trinidad and Tobago crypto ownership',
'Tunisia crypto ownership',
'Turkey crypto ownership',
'Turkmenistan crypto ownership',
'Uganda crypto ownership',
'Ukraine crypto ownership',
'United Arab Emirates crypto ownership',
'United Kingdom crypto ownership',
'United States crypto ownership',
'Uruguay crypto ownership',
'Uzbekistan crypto ownership',
'Venezuela crypto ownership',
'Vietnam crypto ownership',
'Virgin Islands , U.S. crypto ownership',
'Zambia crypto ownership',
'Zimbabwe crypto ownership',
]

output = []

for search in all_search:
       text = search
       output.append(text)



       url = 'https://google.com/search?q=' + text
       A = ("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36",
       "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36",
       "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36",
       )
 
       Agent = A[random.randrange(len(A))]
       
       headers = {'user-agent': Agent}
       r = requests.get(url, headers=headers)
       
       soup = BeautifulSoup(r.text, 'lxml')
       for info in soup.find_all('h3'):
              output.append(info.text)


df = pd.DataFrame(output)

df.to_csv('output3.csv')